//! HTTP conformance against recorded Confluent 7.9 behavior.
//!
//! `tests/http_conformance/scenarios.json` (generated by scenarios.py) holds
//! request sequences over every REST endpoint: valid and invalid input,
//! repeated mutations, missing resources, odd names, mode/config interplay.
//! `golden.json` is what a real Confluent 7.9.0 answered (`run.py record`).
//! Each scenario is replayed here against a fresh in-process server
//! (normalize=false, BACKWARD, like a stock Confluent) and every step must
//! produce the same status and JSON body.
//!
//! Server-assigned ids are compared symbolically (see run.py; the two
//! implementations must stay identical). Divergences are allowed only through
//! the rules below and `allowed.json`, each with its reason.

use std::sync::Arc;

use axum::body::Body;
use axum::http::Request;
use regex::Regex;
use serde_json::{Value, json};
use tower::ServiceExt;

use crate::api;
use crate::auth::Auth;
use crate::model::CompatibilityLevel;
use crate::registry::Registry;
use crate::store::Store;

const CT: &str = "application/vnd.schemaregistry.v1+json";

/// How much of a step's answer is compared.
#[derive(Clone, Copy, PartialEq, Debug)]
enum Cmp {
    /// Status and `error_code` only.
    Code,
    /// Not compared.
    Skip,
    /// Status and `is_compatible` only.
    Verdict,
}

/// Known, deliberate divergences: (scenario#step, comparison, reason).
/// Known, deliberate divergences, from `tests/http_conformance/allowed.json`
/// (shared with run.py): scenario#step, comparison, reason.
fn allowed(root: &str) -> Vec<(String, Cmp, String)> {
    let list: Vec<Value> = serde_json::from_str(&std::fs::read_to_string(format!("{root}/allowed.json")).unwrap()).unwrap();
    list.iter()
        .map(|e| {
            let cmp = match e["cmp"].as_str().unwrap() {
                "skip" => Cmp::Skip,
                "code" => Cmp::Code,
                "verdict" => Cmp::Verdict,
                other => panic!("unknown cmp {other}"),
            };
            (e["step"].as_str().unwrap().to_string(), cmp, e["reason"].as_str().unwrap().to_string())
        })
        .collect()
}

/// Confluent's `QualifiedSubject` context of a (decoded) subject.
fn context_of(subject: &str) -> String {
    match subject.strip_prefix(":.") {
        Some(rest) => match rest.find(':') {
            Some(i) => subject[1..2 + i].to_string(),
            None => subject[1..].to_string(),
        },
        None => ".".to_string(),
    }
}

/// The context a step's ids live in (see run.py).
fn step_context(path: &str) -> String {
    let (p, q) = path.split_once('?').unwrap_or((path, ""));
    let segs: Vec<&str> = p.trim_matches('/').split('/').collect();
    if segs.len() > 1 && segs[0] == "contexts" {
        let c = api::percent_decode(segs[1]);
        return if c.starts_with('.') { c } else { format!(".{c}") };
    }
    for i in 0..segs.len().saturating_sub(1) {
        if segs[i] == "subjects" {
            return context_of(&api::percent_decode(segs[i + 1]));
        }
    }
    for kv in q.split('&') {
        if let Some(v) = kv.strip_prefix("subject=") {
            return context_of(&api::percent_decode(v));
        }
    }
    ".".to_string()
}

/// (context, server id) <-> "$idN", in first-seen order.
struct Ids {
    to_sym: Vec<((String, i64), String)>,
    ctx: String,
}

impl Ids {
    fn new() -> Self {
        Self { to_sym: Vec::new(), ctx: ".".into() }
    }
    fn sym(&mut self, real: i64, ctx: &str) -> String {
        let key = (ctx.to_string(), real);
        if let Some((_, s)) = self.to_sym.iter().find(|(k, _)| *k == key) {
            return s.clone();
        }
        let s = format!("$id{}", self.to_sym.len() + 1);
        self.to_sym.push((key, s.clone()));
        s
    }
    fn real(&self, n: &str) -> Option<i64> {
        self.to_sym.iter().find(|(_, s)| s[3..] == *n).map(|((_, r), _)| *r)
    }
    fn subst_path(&self, p: &str) -> String {
        let re = Regex::new(r"\{\$id(\d+)\}").unwrap();
        re.replace_all(p, |c: &regex::Captures| match self.real(&c[1]) {
            Some(r) => r.to_string(),
            None => c[0].to_string(),
        })
        .into_owned()
    }
    fn subst_body(&self, v: &Value) -> Value {
        let re = Regex::new(r"^\{\$id(\d+)\}$").unwrap();
        match v {
            Value::String(s) => match re.captures(s).and_then(|c| self.real(&c[1])) {
                Some(r) => json!(r),
                None => v.clone(),
            },
            Value::Array(a) => Value::Array(a.iter().map(|x| self.subst_body(x)).collect()),
            Value::Object(o) => Value::Object(o.iter().map(|(k, x)| (k.clone(), self.subst_body(x))).collect()),
            _ => v.clone(),
        }
    }
}

fn keep_filter(body: Value, keep: &[Value]) -> Value {
    let ok = |s: &str| {
        keep.iter().filter_map(Value::as_str).any(|k| match k.strip_prefix('=') {
            Some(exact) => s == exact,
            None => s.starts_with(k),
        })
    };
    match body {
        Value::Array(a) => Value::Array(
            a.into_iter()
                .filter(|x| match x {
                    Value::String(s) => ok(s),
                    Value::Object(o) => ok(o.get("subject").and_then(Value::as_str).unwrap_or("")),
                    _ => ok(""),
                })
                .collect(),
        ),
        other => other,
    }
}

fn symbolize(body: Value, ids: &mut Ids, id_list: bool) -> Value {
    let msg_id = Regex::new(r"(Schema |with id |input id )(-?\d+)").unwrap();
    fn walk(v: Value, ids: &mut Ids, msg_id: &Regex, ctx: &str) -> Value {
        match v {
            Value::Object(o) => {
                let ctx = o.get("subject").and_then(Value::as_str).map(context_of).unwrap_or_else(|| ctx.to_string());
                Value::Object(
                o.into_iter()
                    .map(|(k, x)| {
                        let x = match (&*k, x) {
                            ("id" | "maxId", Value::Number(n)) if n.is_i64() => json!(ids.sym(n.as_i64().unwrap(), &ctx)),
                            ("message", Value::String(s)) => {
                                let mut out = String::new();
                                let mut last = 0;
                                for c in msg_id.captures_iter(&s) {
                                    let m = c.get(0).unwrap();
                                    out.push_str(&s[last..m.start()]);
                                    out.push_str(&c[1]);
                                    out.push_str(&ids.sym(c[2].parse().unwrap(), &ctx));
                                    last = m.end();
                                }
                                out.push_str(&s[last..]);
                                Value::String(out)
                            }
                            (_, x) => walk(x, ids, msg_id, &ctx),
                        };
                        (k, x)
                    })
                    .collect(),
                )
            }
            Value::Array(a) => Value::Array(a.into_iter().map(|x| walk(x, ids, msg_id, ctx)).collect()),
            v => v,
        }
    }
    let ctx = ids.ctx.clone();
    match body {
        Value::Array(a) if id_list => Value::Array(
            a.into_iter().map(|x| if let Some(n) = x.as_i64() { json!(ids.sym(n, &ctx)) } else { x }).collect(),
        ),
        b => walk(b, ids, &msg_id, &ctx),
    }
}

async fn send(app: &api::Service, st: &Value, ids: &mut Ids) -> Value {
    ids.ctx = step_context(st["p"].as_str().unwrap());
    let path = ids.subst_path(st["p"].as_str().unwrap());
    let body = if let Some(raw) = st.get("raw").and_then(Value::as_str) {
        Some(raw.as_bytes().to_vec())
    } else {
        st.get("b").map(|b| serde_json::to_vec(&ids.subst_body(b)).unwrap())
    };
    let mut req = Request::builder().method(st["m"].as_str().unwrap()).uri(&path);
    // Like Python's urllib: a POST/PUT body without an explicit Content-Type is form-encoded.
    let ct = st.get("ct").and_then(Value::as_str).unwrap_or(CT);
    if body.is_some() {
        req = req.header("content-type", if ct.is_empty() { "application/x-www-form-urlencoded" } else { ct });
    }
    let req = req.body(body.map(Body::from).unwrap_or_else(Body::empty)).unwrap();
    let resp = app.clone().oneshot(req).await.unwrap();
    let status = resp.status().as_u16();
    let bytes = axum::body::to_bytes(resp.into_body(), usize::MAX).await.unwrap();
    let text = String::from_utf8_lossy(&bytes).into_owned();
    let mut body = if text.trim().is_empty() {
        json!({"text": text})
    } else {
        serde_json::from_str(&text).unwrap_or_else(|_| json!({"text": text}))
    };
    if let Some(keep) = st.get("keep").and_then(Value::as_array) {
        body = keep_filter(body, keep);
    }
    json!({"status": status, "body": symbolize(body, ids, st.get("ids").and_then(Value::as_bool).unwrap_or(false))})
}

fn fresh_app() -> (api::Service, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::open(dir.path(), false).unwrap();
    let snap = store.load_snapshot().unwrap();
    let registry = Registry::new(store, snap, CompatibilityLevel::Backward, "test".into(), 1000, false);
    // One container, reached on any host - what a deployment that configures
    // none gets, and what the recorded corpus was taken against.
    let containers = crate::containers::Containers::new(
        &[],
        std::collections::HashMap::from([(crate::tenant::TenantId::default_tenant(), Arc::new(registry))]),
    );
    let shared = api::Shared { containers: Arc::new(containers), auth: Arc::new(Auth::disabled()) };
    (api::service(shared, 16 << 20), dir)
}

fn error_code(v: &Value) -> Option<i64> {
    v["body"].get("error_code").and_then(Value::as_i64)
}

/// Rules that apply everywhere, each with its reason.
fn rule(want: &Value) -> Option<(Cmp, &'static str)> {
    let msg = want["body"].get("message").and_then(Value::as_str).unwrap_or("");
    if want["status"] == 400 && error_code(want) == Some(400) {
        return Some((Cmp::Code, "Jackson's request-body parse error text is not reproduced"));
    }
    if error_code(want) == Some(500) {
        return Some((Cmp::Skip, "Confluent crashes (500); we answer with a proper error or result"));
    }
    let parser_detail = |m: &str| m.contains("details: com.fasterxml.jackson") || m.contains("details: Could not parse Protobuf");
    if parser_detail(msg) {
        return Some((Cmp::Code, "Jackson/Wire parser error detail text is not reproduced"));
    }
    if want["body"]["messages"].as_array().is_some_and(|m| m.iter().filter_map(Value::as_str).any(parser_detail)) {
        return Some((Cmp::Verdict, "Jackson/Wire parser error detail text is not reproduced"));
    }
    None
}

#[test]
fn http_conformance() {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/http_conformance");
    let scenarios: Vec<Value> = serde_json::from_str(&std::fs::read_to_string(format!("{root}/scenarios.json")).unwrap()).unwrap();
    let golden: Value = serde_json::from_str(&std::fs::read_to_string(format!("{root}/golden.json")).unwrap()).unwrap();
    let only = std::env::var("SCENARIO").ok();
    let allowed_list = allowed(root);
    let rt = tokio::runtime::Builder::new_multi_thread().enable_all().build().unwrap();
    let mut failures = Vec::new();
    let mut used = std::collections::HashSet::new();
    let (mut total, mut relaxed) = (0, 0);
    for sc in &scenarios {
        let name = sc["name"].as_str().unwrap();
        if only.as_deref().is_some_and(|o| o != name) {
            continue;
        }
        let want_all = golden[name].as_array().unwrap_or_else(|| panic!("no golden for {name}"));
        let (app, _dir) = fresh_app();
        let mut ids = Ids::new();
        for (i, (st, want)) in sc["steps"].as_array().unwrap().iter().zip(want_all).enumerate() {
            total += 1;
            let got = rt.block_on(send(&app, st, &mut ids));
            let key = format!("{name}#{i}");
            let allowed = allowed_list.iter().find(|(k, ..)| *k == key).map(|(_, c, r)| (*c, r.as_str()));
            if allowed.is_some() {
                used.insert(key.clone());
            }
            let relax: Option<(Cmp, &str)> = allowed.or_else(|| rule(want));
            let same_status = want["status"] == got["status"];
            let ok = match (st.get("cmp").and_then(Value::as_str), relax) {
                (_, Some((Cmp::Skip, _))) => true,
                (Some("status"), _) => same_status,
                (_, Some((Cmp::Code, _))) => same_status && error_code(want) == error_code(&got),
                (_, Some((Cmp::Verdict, _))) => same_status && want["body"]["is_compatible"] == got["body"]["is_compatible"],
                (Some("keys"), _) => {
                    let keys = |v: &Value| {
                        v["body"].as_object().map(|o| {
                            let mut k: Vec<String> = o.keys().cloned().collect();
                            k.sort();
                            k
                        })
                    };
                    same_status && keys(want) == keys(&got)
                }
                _ => want == &got,
            };
            if relax.is_some() && want != &got {
                relaxed += 1;
            }
            if !ok {
                failures.push(format!(
                    "{key} {} {}\n    request:   {}\n    confluent: {} {}\n    ours:      {} {}",
                    st["m"].as_str().unwrap(),
                    st["p"].as_str().unwrap(),
                    st.get("b").or(st.get("raw")).map(|b| b.to_string()).unwrap_or_default().chars().take(300).collect::<String>(),
                    want["status"],
                    want["body"].to_string().chars().take(700).collect::<String>(),
                    got["status"],
                    got["body"].to_string().chars().take(700).collect::<String>(),
                ));
            }
            // Teardown steps are irrelevant here: every scenario gets a fresh server.
        }
    }
    let stale: Vec<&str> =
        allowed_list.iter().map(|(k, ..)| k.as_str()).filter(|k| only.is_none() && !used.contains(*k)).collect();
    assert!(stale.is_empty(), "ALLOWED entries that match no step: {stale:?}");
    assert!(
        failures.is_empty(),
        "{} of {total} steps differ from Confluent ({relaxed} relaxed by documented rules):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
